// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyomkcbiojpnfoarbxkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5b21rY2Jpb2pwbmZvYXJieGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTI1NzAsImV4cCI6MjA1ODU2ODU3MH0.GyrjydrF-h-5cqTwDADnV2O0enT9GY9kmbF1iebIqIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);